pages:
  - Home: 'index.md'
  - Core Components: 'core.md'
  - Tutorials:
    - Executing a SPARQL query: 'tutorials/sparql.md'
    - Including Comunica in your project: 'tutorials/including-comunica.md'
    - Creating a configuration: 'tutorials/configuration.md'
    - Creating a module: 'tutorials/module.md'
  - Actor categories:
    - Overview: 'actors/actors.md'
    - Algebra actors: 'actors/algebra.md'
    - Init actors: 'actors/init.md'
    - Join actors: 'actors/join.md'
    - Metadata actors: 'actors/metadata.md'
    - Quad pattern resolvers: 'actors/quads.md'
    - Serialization actors: 'actors/serialization.md'

site_name: Comunica

markdown_extensions:
  - admonition

theme: readthedocs
